apiVersion: postgres.operchain.demo/v1alpha1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: instance
    app.kubernetes.io/instance: instance-sample
    app.kubernetes.io/part-of: demo-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: demo-operator
  name: instance-sample
spec:
  # TODO(user): Add fields here
