name: Apply Version Tag

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get version number
      id: version
      run: |
        echo version=$(make print-version) >> $GITHUB_OUTPUT
    - name: Check for existing tag
      run: |
        if git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
          echo "error: tag v${{ steps.version.outputs.version }} already exists"
          exit 1
        fi
    - name: Create tag
      if: github.ref_name == 'main'
      run: |
        git config --local url."https://smxlong:${{ secrets.PUBLISH_TOKEN }}@${{ github.repository }}".insteadOf "https://${{ github.repository }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git tag "v${{ steps.version.outputs.version }}"
        git push origin "v${{ steps.version.outputs.version }}"
